# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'
services:
  wordpress:
    image: leloimr/anesta:latest
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - '80:8080'
    #   - '443:8443'
    # volumes:
    #   - 'wordpress_data:/bitnami/wordpress'
    # environment:
    #   # ALLOW_EMPTY_PASSWORD is recommended only for development.
    #   - ALLOW_EMPTY_PASSWORD=yes
    #   - WORDPRESS_DATABASE_HOST=mariadb
    #   - WORDPRESS_DATABASE_PORT_NUMBER=3306
    #   - WORDPRESS_DATABASE_USER=bn_wordpress
    #   - WORDPRESS_DATABASE_NAME=bitnami_wordpress
# volumes:
#   mariadb_data:
#     driver: local
#   wordpress_data:
#     driver: local